### ISSUE TITLE
NL-SfB Classification update

### ISSUE THREAD

**Issue by MennoMekes** [Moult/IfcClassification#1]
Hi,

I noticed one of the buildingcodes you provide is outdated.
It's the NL-SfB Classification.
The one you provided is the old, 205 version. In December 2019 there has been an update.
The contents comes directly from the provided .xls-file from BIMloket / Ketenstandaard.

Link to my github where the file is:
https://github.com/MennoMekes/NL-SfB-tabel-1-Classification/blob/BlenderBIM/NL-SfB%20tabel%201%20Classification.ifc

link to the correct classification:
https://stprodeuwmystabu002stor.blob.core.windows.net/overig/NL-SfB_Tabel_0-4_Update-V201912.xlsx

link to my article on OsArch:
https://community.osarch.org/discussion/1306/blenderbim-dutch-nl-sfb-classificationcode-updated/p1?new=1

(Sorry, I don't know how github works woith pull-request etc.)

**Comment by Moult** [comment]
Thanks so much! I've added it.

**Comment by MennoMekes** [comment]
Thanks for adding the file.
I have anonther one  that is actually the current version.
Somehow nobody, including me, noticed there was a new update over a year ago.

On the website you can still download all versions (2005, 2019 and 2021)
see also: https://www.bimloket.nl/p/715/Tabellen

The link to the up-to-date file remains the same:
https://github.com/MennoMekes/NL-SfB-tabel-1-Classification/blob/BlenderBIM/NL-SfB%20tabel%201%20Classification.ifc

Thanks a lot!
